#pragma once
#include <core/event.h>

using namespace UM;


struct CameraPose {
    vec3 pivot = {};
    Quaternion orientation = {}; // transforms camera-local vectors into world-space vectors
    double distance = 1;

    mat4x4 matrix() const;
    vec3 position() const;
    vec3 forward()  const;
    vec3 up()       const;
    vec3 right()    const;

    // rotate the camera around the pivot
    // q is a world-space rotation
    void rotate(Quaternion q);

    // translate the camera and pivot together in world space
    void translate(vec3 delta);

    // pan in camera/screen space
    void pan(vec2 delta);
};

struct OrthographicProjection {
    vec2 center = {};
    double view_height = 2; // in world units
    double aspect = 1;
    double near = -1e+2;
    double far  = +1e+2;

    void set_aspect_ratio(double a);
    mat4x4 matrix() const;
};

struct TrackBallCamera {
    CameraPose pose;
    OrthographicProjection projection;
    static constexpr double wheel_zoom_speed = 1e-1;
    static constexpr double min_view_height  = 1e-6;

    // compute the rotation generated by an arcball drag
    // previous and current are mouse positions in pixel coordinates;
    // viewport is the viewport size in pixels
    Quaternion arcball_rotation(vec2 previous, vec2 current, vec2 viewport) const;

    void resize(double width, double height);
    void zoom(double wheel);
    void pan(vec2 delta, vec2 viewport);
    void rotate(vec2 previous, vec2 current, vec2 viewport);
    mat4x4 projection_matrix() const ;
    mat4x4 view_matrix() const ;

    float* projection_ptr() const;
    float* view_ptr() const;
    float* inverse_projection_ptr() const;
    void handle(Event event);
};


